name: RockiTech Blog

description: "A blog dedicated to articles related to things like web development, design, server management..."
url: "https://rockitech.net"
enforce_ssl: "rockitech.net"

logo: /static/img/logo.png


google_verify: "_mjuCILje1KbiyITzjH9RaUctxe8KvIRyJyMgY8M62M"

facebook:
  app_id: 1830897697239746
 
defaults:
  - scope:
      path: ""
    values:
      image:
        path: "/static/img/logo-card.png"
        height: 500
        width: 500

markdown:    kramdown
highlighter: pygments
kramdown:  
  parse_block_html: true

permalink: /p/:categories/:title.html

related_posts_max: 4

paginate: 6
paginate_path: "/page-:num/"

gems:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
  - jekyll-admin